// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Review_Site.Data;

#nullable disable

namespace Review_Site.Migrations
{
    [DbContext(typeof(ReviewSiteContext))]
    [Migration("20230319014025_Migration1")]
    partial class Migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Review_Site.Models.DestinationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("TourDuration")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Tokyo",
                            Country = "Japan",
                            Description = "Tokyo, Japan’s busy capital, mixes the ultramodern and the traditional, from neon-lit skyscrapers to historic temples. The opulent Meiji Shinto Shrine is known for its towering gate and surrounding woods. The Imperial Palace sits amid large public gardens. The city's many museums offer exhibits ranging from classical art (in the Tokyo National Museum) to a reconstructed kabuki theater (in the Edo-Tokyo Museum).",
                            ImageList = "\\Images\\Tokyo11.jpg,\\Images\\Tokyo12.jpg,\\Images\\Tokyo13.jpg,\\Images\\Tokyo14.jpg,\\Images\\Tokyo15.jpg,\\Images\\Tokyo16.jpg,\\Images\\Tokyo17.jpg,\\Images\\Tokyo18.jpg",
                            ImageURL = "\\Images\\Tokyo1.jpg",
                            Name = "Tour of Tokyo",
                            Price = 8000,
                            TourDuration = 10
                        },
                        new
                        {
                            Id = 2,
                            City = "Rome",
                            Country = "Italy",
                            Description = "Rome was called the “Eternal City” by the ancient Romans because they believed that no matter what happened in the rest of the world, the city of Rome would always remain standing. Exploring the city center by foot surrounded by glorious monuments and colossal remains takes you back in time to the “glory that was Rome”. If you want to see history come to life like never before visit Rome and witness it all aorund you.",
                            ImageList = "\\Images\\Rome11.jpg,\\Images\\Rome12.jpg,\\Images\\Rome13.jpg,\\Images\\Rome14.jpg,\\Images\\Rome15.jpg,\\Images\\Rome16.jpg,\\Images\\Rome17.jpg,\\Images\\Rome18.jpg",
                            ImageURL = "\\Images\\Rome1.jpg",
                            Name = "Tour of Rome",
                            Price = 10000,
                            TourDuration = 7
                        },
                        new
                        {
                            Id = 3,
                            City = "Paris",
                            Country = "France",
                            Description = "Paris, France's capital, is a major European city and a global center for art, fashion, gastronomy and culture. Its 19th-century cityscape is crisscrossed by wide boulevards and the River Seine. Beyond such landmarks as the Eiffel Tower and the 12th-century, Gothic Notre-Dame cathedral, the city is known for its cafe culture and designer boutiques along the Rue du Faubourg Saint-Honoré. ",
                            ImageList = "\\Images\\Paris11.jpg,\\Images\\Paris12.jpg,\\Images\\Paris13.jpg,\\Images\\Paris14.jpg,\\Images\\Paris15.jpg,\\Images\\Paris16.jpg,\\Images\\Paris17.jpg,\\Images\\Paris18.jpg",
                            ImageURL = "\\Images\\Paris1.jpg",
                            Name = "Tour of Paris",
                            Price = 7000,
                            TourDuration = 6
                        },
                        new
                        {
                            Id = 4,
                            City = "Random Crater",
                            Country = "Unknown",
                            Description = "See what no man in history has seen. Be the first to discover the Red Planet. This is a once in a lifetime opportunity.  Travel along with the one and only Elon Musk himself on multibillion dollar spaceship x. Its dangerous, its thrilling, its ridiculous. You can be the first to set your foot and leave human mark on the red planet. Do you have what it takes? Mainly the money? Go and Find out! ",
                            ImageList = "\\Images\\Mars11.jpg,\\Images\\Mars12.jpg,\\Images\\Mars13.jpg,\\Images\\Mars14.jpg,\\Images\\Mars15.jpg,\\Images\\Mars16.jpg,\\Images\\Mars17.jpg,\\Images\\Mars18.jpg,",
                            ImageURL = "\\Images\\Mars1.jpg",
                            Name = "Tour of Mars",
                            Price = 1000000,
                            TourDuration = 2156
                        });
                });

            modelBuilder.Entity("Review_Site.Models.ReviewModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DestinationsId")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StarRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DestinationsId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Awesome!! Love every minute. Definetly recomend it!!",
                            DestinationsId = 1,
                            ImageURL = "\\Images\\Kate.png",
                            ReviewerName = "Kate Johnson",
                            StarRating = "5",
                            Timestamp = new DateTime(2002, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Content = "Best trip ever. I want to do it again!!! Friggin Awesome!!",
                            DestinationsId = 1,
                            ImageURL = "\\Images\\TokyoJohn.png",
                            ReviewerName = "John Chelios",
                            StarRating = "4",
                            Timestamp = new DateTime(2005, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Content = "So glad i went. It was a trip of a lifetime. I want to do it again soon!!",
                            DestinationsId = 1,
                            ImageURL = "\\Images\\TokyoKaren.png",
                            ReviewerName = "Karen Smith",
                            StarRating = "5",
                            Timestamp = new DateTime(2010, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Content = "Really enjoyed the sights and scenery. Glad I made the decision to go. Highly recomend it!",
                            DestinationsId = 1,
                            ImageURL = "\\Images\\TokyoHannah.png",
                            ReviewerName = "Hannah Simms",
                            StarRating = "4",
                            Timestamp = new DateTime(2007, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Content = "Awesome!! Love every minute. Definetly recomend it!!",
                            DestinationsId = 2,
                            ImageURL = "\\Images\\James.png",
                            ReviewerName = "James Olson",
                            StarRating = "5",
                            Timestamp = new DateTime(2002, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Content = "Best trip ever. I want to do it again!!! Friggin Awesome!!",
                            DestinationsId = 2,
                            ImageURL = "\\Images\\RomeEric.png",
                            ReviewerName = "Eric Lindros",
                            StarRating = "4",
                            Timestamp = new DateTime(2005, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Content = "So glad i went. It was a trip of a lifetime. I want to do it again soon!!",
                            DestinationsId = 2,
                            ImageURL = "\\Images\\RomeFred.png",
                            ReviewerName = "Fred Mayer",
                            StarRating = "5",
                            Timestamp = new DateTime(2010, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Content = "Really enjoyed the sights and scenery. Glad I made the decision to go. Highly recomend it!",
                            DestinationsId = 2,
                            ImageURL = "\\Images\\RomeErika.png",
                            ReviewerName = "Erika Stevenson",
                            StarRating = "4",
                            Timestamp = new DateTime(2007, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Content = "Awesome!! Love every minute. Definetly recomend it!!",
                            DestinationsId = 3,
                            ImageURL = "\\Images\\ParisGary.jpg",
                            ReviewerName = "Gary James",
                            StarRating = "5",
                            Timestamp = new DateTime(2002, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Content = "Best trip ever. I want to do it again!!! Friggin Awesome!!",
                            DestinationsId = 3,
                            ImageURL = "\\Images\\ParisAngela.jpg",
                            ReviewerName = "Angela Salisbury",
                            StarRating = "4",
                            Timestamp = new DateTime(2005, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Content = "So glad i went. It was a trip of a lifetime. I want to do it again soon!!",
                            DestinationsId = 3,
                            ImageURL = "\\Images\\ParisLily.png",
                            ReviewerName = "Lily Lewis",
                            StarRating = "5",
                            Timestamp = new DateTime(2010, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Content = "Awesome!! Love every minute. Definetly recomend it!!",
                            DestinationsId = 4,
                            ImageURL = "\\Images\\MarsKurt.png",
                            ReviewerName = "Kurt Jackson",
                            StarRating = "5",
                            Timestamp = new DateTime(2002, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Content = "Best trip ever. I want to do it again!!! Friggin Awesome!!",
                            DestinationsId = 4,
                            ImageURL = "\\Images\\MarsJim.png",
                            ReviewerName = "Jim Norton",
                            StarRating = "4",
                            Timestamp = new DateTime(2005, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Content = "So glad i went. It was a trip of a lifetime. I want to do it again soon!!",
                            DestinationsId = 4,
                            ImageURL = "\\Images\\MarsSpaceman.jpg",
                            ReviewerName = "Steven Curtis",
                            StarRating = "5",
                            Timestamp = new DateTime(2010, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Content = "It's decent",
                            DestinationsId = 4,
                            ImageURL = "\\Images\\MarsSpaceman 2.jpg",
                            ReviewerName = "Lawrence Jackson",
                            StarRating = "3",
                            Timestamp = new DateTime(2002, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Review_Site.Models.ReviewModel", b =>
                {
                    b.HasOne("Review_Site.Models.DestinationModel", "Destinations")
                        .WithMany("Reviews")
                        .HasForeignKey("DestinationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destinations");
                });

            modelBuilder.Entity("Review_Site.Models.DestinationModel", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
